import { writeFile } from "node:fs/promises";
import type { ReviewResult, ReviewFinding } from "../ai/client.js";

const SEVERITY_EMOJI: Record<ReviewFinding["severity"], string> = {
  critical: "🔴",
  warning: "🟡",
  suggestion: "🔵",
  nitpick: "⚪",
};

const SEVERITY_ORDER: ReviewFinding["severity"][] = [
  "critical",
  "warning",
  "suggestion",
  "nitpick",
];

function scoreEmoji(score: number): string {
  if (score >= 8) return "✅";
  if (score >= 5) return "⚠️";
  return "❌";
}

export function buildMarkdown(
  result: ReviewResult,
  context: { label: string; prTitle?: string; model?: string }
): string {
  const lines: string[] = [];

  lines.push("# 🍌 Peely Code Review");
  lines.push("");
  lines.push(`**Target:** ${context.label}`);
  if (context.prTitle) {
    lines.push(`**PR:** ${context.prTitle}`);
  }
  lines.push(`**Date:** ${new Date().toISOString().split("T")[0]}`);
  if (context.model) {
    lines.push(`**Model:** ${context.model}`);
  }
  lines.push("");

  lines.push("---");
  lines.push("");

  lines.push(`## Score: ${result.overallScore}/10 ${scoreEmoji(result.overallScore)}`);
  lines.push("");
  lines.push(result.summary);
  lines.push("");

  if (result.findings.length === 0) {
    lines.push("**No issues found. Looks good!** 🎉");
    lines.push("");
    return lines.join("\n");
  }

  const counts = { critical: 0, warning: 0, suggestion: 0, nitpick: 0 };
  for (const f of result.findings) {
    counts[f.severity]++;
  }

  lines.push("## Summary");
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("|----------|-------|");
  for (const sev of SEVERITY_ORDER) {
    if (counts[sev] > 0) {
      lines.push(`| ${SEVERITY_EMOJI[sev]} ${sev} | ${counts[sev]} |`);
    }
  }
  lines.push("");

  lines.push("---");
  lines.push("");

  lines.push("## Findings");
  lines.push("");

  const grouped = new Map<ReviewFinding["severity"], ReviewFinding[]>();
  for (const sev of SEVERITY_ORDER) {
    const items = result.findings.filter((f) => f.severity === sev);
    if (items.length > 0) grouped.set(sev, items);
  }

  for (const [severity, findings] of grouped) {
    lines.push(`### ${SEVERITY_EMOJI[severity]} ${severity.charAt(0).toUpperCase() + severity.slice(1)}`);
    lines.push("");

    for (const f of findings) {
      const location = f.line ? `${f.file}:${f.line}` : f.file;
      lines.push(`#### ${f.title}`);
      lines.push("");
      lines.push(`📍 \`${location}\``);
      lines.push("");
      lines.push(f.description);

      if (f.suggestion) {
        lines.push("");
        lines.push(`> **Suggestion:** ${f.suggestion}`);
      }

      lines.push("");
    }
  }

  lines.push("---");
  lines.push("");
  lines.push("*Generated by [Peely](https://github.com/peely) — AI Code Reviewer*");
  lines.push("");

  return lines.join("\n");
}

export async function writeMarkdownReport(
  filepath: string,
  result: ReviewResult,
  context: { label: string; prTitle?: string; model?: string }
): Promise<void> {
  const content = buildMarkdown(result, context);
  await writeFile(filepath, content, "utf-8");
}
